### ISSUE TITLE
Standard

### ISSUE THREAD

**Issue by eptaccio** [msfidelis/raj#3]
O que acha de aplicarmos o standard.js?

**Comment by msfidelis** [comment]
Gosto da ideia de manter um padrão. 
Sou bem a favor do standard.js
> https://standardjs.com/

**Comment by msfidelis** [comment]
Eu gosto bastante do JS Hint. 
Pra projetos pequenos não sei qual é melhor.

**Comment by eptaccio** [comment]
Acho que o standard casa com qual com qualquer projeto ehuheu
